configure: Try qmake-qt5 if qmake default doesn't work

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4457,8 +4457,12 @@ echo "License: $license"
 # Torc
 
 # Qt
-if ! expr $($qmake -query QT_VERSION) : "5\.[0-9]\.[0-9]" >/dev/null; then
-  die "qmake for Qt5.0 or newer not found.\nPlease specify the correct qmake with --qmake="
+is_qmake5(){
+    $1 --version 2>&1 | egrep -q -e "Qt version 5\.[0-9]\.[0-9]"
+}
+
+if ! is_qmake5 $qmake ; then
+    is_qmake5 qmake-qt5 && qmake=qmake-qt5 || die "qmake for Qt5.0 or newer not found. Please specify the correct qmake with --qmake="
 fi
 
 if test $target_os = mingw32 ; then
diff --git a/configure.diff b/configure.diff
--- a/configure.diff
+++ b/configure.diff
@@ -1,5 +1,5 @@
 --- libs/libtorc-av/configure	2013-05-01 20:34:52.277266987 +0100
-+++ configure	2013-10-09 08:46:40.685379218 +0100
++++ configure	2013-10-22 19:14:13.635372434 +0100
 @@ -1,6 +1,6 @@
  #!/bin/sh
  #
@@ -396,15 +396,19 @@
  echo "install prefix            $prefix"
  echo "source path               $source_path"
  echo "C compiler                $cc"
-@@ -4348,6 +4454,124 @@
+@@ -4348,6 +4454,128 @@
  
  echo "License: $license"
  
 +# Torc
 +
 +# Qt
-+if ! expr $($qmake -query QT_VERSION) : "5\.[0-9]\.[0-9]" >/dev/null; then
-+  die "qmake for Qt5.0 or newer not found.\nPlease specify the correct qmake with --qmake="
++is_qmake5(){
++    $1 --version 2>&1 | egrep -q -e "Qt version 5\.[0-9]\.[0-9]"
++}
++
++if ! is_qmake5 $qmake ; then
++    is_qmake5 qmake-qt5 && qmake=qmake-qt5 || die "qmake for Qt5.0 or newer not found. Please specify the correct qmake with --qmake="
 +fi
 +
 +if test $target_os = mingw32 ; then
@@ -521,7 +525,7 @@
  echo "Creating config.mak and config.h..."
  
  test -e Makefile || $ln_s "$source_path/Makefile" .
-@@ -4358,20 +4582,25 @@
+@@ -4358,20 +4586,25 @@
  
  cat > config.mak <<EOF
  # Automatically generated by configure - do not modify!
@@ -557,7 +561,7 @@
  CC_IDENT=$cc_ident
  ARCH=$arch
  CC=$cc
-@@ -4404,11 +4633,20 @@
+@@ -4404,11 +4637,20 @@
  CXX_O=$CXX_O
  LD_O=$LD_O
  LD_LIB=$LD_LIB
@@ -579,7 +583,7 @@
  YASMFLAGS=$YASMFLAGS
  BUILDSUF=$build_suffix
  PROGSSUF=$progs_suffix
-@@ -4448,7 +4686,7 @@
+@@ -4448,7 +4690,7 @@
  CFLAGS-ffplay=$sdl_cflags
  ZLIB=$($ldflags_filter -lz)
  LIB_INSTALL_EXTRA_CMD=$LIB_INSTALL_EXTRA_CMD
@@ -588,7 +592,7 @@
  COMPAT_OBJS=$compat_objs
  EXEOBJS=$exeobjs
  INSTALL=$install
-@@ -4456,20 +4694,20 @@
+@@ -4456,20 +4698,20 @@
  SLIBNAME=${SLIBNAME}
  SLIBNAME_WITH_VERSION=${SLIBNAME_WITH_VERSION}
  SLIBNAME_WITH_MAJOR=${SLIBNAME_WITH_MAJOR}
@@ -613,7 +617,7 @@
      eval $(awk "/#define ${name}_VERSION_M/ { print \$2 \"=\" \$3 }" "$file")
      eval ${name}_VERSION=\$${name}_VERSION_MAJOR.\$${name}_VERSION_MINOR.\$${name}_VERSION_MICRO
      eval echo "${lcname}_VERSION=\$${name}_VERSION" >> config.mak
-@@ -4513,13 +4751,21 @@
+@@ -4513,13 +4755,21 @@
                                       $ALL_COMPONENTS    \
  
  echo "#endif /* FFMPEG_CONFIG_H */" >> $TMPH
@@ -639,7 +643,7 @@
  
  cat > $TMPH <<EOF
  /* Generated by ffconf */
-@@ -4531,101 +4777,9 @@
+@@ -4531,101 +4781,9 @@
  
  echo "#endif /* AVUTIL_AVCONFIG_H */" >> $TMPH
  
