configure: Update configure.diff

diff --git a/configure.diff b/configure.diff
--- a/configure.diff
+++ b/configure.diff
@@ -1,5 +1,5 @@
---- libs/libtorc-av/configure	2013-05-01 20:34:52.277266987 +0100
-+++ configure	2013-12-12 18:16:12.588124317 +0000
+--- libs/libtorc-av/configure	2013-05-01 10:16:11.000000000 +0100
++++ configure	2014-02-19 10:20:08.000000000 +0000
 @@ -1,6 +1,6 @@
  #!/bin/sh
  #
@@ -333,6 +333,15 @@
  enabled libbluray  && require libbluray libbluray/bluray.h bd_open -lbluray
  enabled libcelt    && require libcelt celt/celt.h celt_decode -lcelt0 &&
                        { check_lib celt/celt.h celt_decoder_create_custom -lcelt0 ||
+@@ -3900,7 +3985,7 @@
+ enabled libfdk_aac && require  libfdk_aac fdk-aac/aacenc_lib.h aacEncOpen -lfdk-aac
+ flite_libs="-lflite_cmu_time_awb -lflite_cmu_us_awb -lflite_cmu_us_kal -lflite_cmu_us_kal16 -lflite_cmu_us_rms -lflite_cmu_us_slt -lflite_usenglish -lflite_cmulex -lflite"
+ enabled libflite   && require2 libflite "flite/flite.h" flite_init $flite_libs
+-enabled libfreetype && require_pkg_config freetype2 "ft2build.h freetype/freetype.h" FT_Init_FreeType
++enabled libfreetype && check_pkg_config freetype2 "ft2build.h freetype/freetype.h" FT_Init_FreeType || disable libfreetype
+ enabled libgsm     && { for gsm_hdr in "gsm.h" "gsm/gsm.h"; do
+                             check_lib "${gsm_hdr}" gsm_create -lgsm && break;
+                         done || die "ERROR: libgsm not found"; }
 @@ -3953,6 +4038,9 @@
                          check_lib openssl/ssl.h SSL_library_init -lssl32 -leay32 ||
                          check_lib openssl/ssl.h SSL_library_init -lssl -lcrypto -lws2_32 -lgdi32 ||
@@ -401,7 +410,7 @@
  echo "install prefix            $prefix"
  echo "source path               $source_path"
  echo "C compiler                $cc"
-@@ -4348,6 +4450,107 @@
+@@ -4348,6 +4450,108 @@
  
  echo "License: $license"
  
@@ -494,6 +503,7 @@
 +echo "libdns_sd (Bonjour) enabled  ${libdns_sd-no}"
 +echo "libass enabled               ${libass-no}"
 +echo "libfreetype enabled          ${libfreetype-no}"
++echo "BDJ support enabled          ${libfreetype-no}"
 +echo "libcdio (CD input) enabled   ${libcdio_indev-no}"
 +if test $target_os = "linux"; then
 +    echo "vaapi enabled                ${vaapi-no}"
@@ -509,7 +519,7 @@
  echo "Creating config.mak and config.h..."
  
  test -e Makefile || $ln_s "$source_path/Makefile" .
-@@ -4358,20 +4561,25 @@
+@@ -4358,20 +4562,25 @@
  
  cat > config.mak <<EOF
  # Automatically generated by configure - do not modify!
@@ -545,7 +555,7 @@
  CC_IDENT=$cc_ident
  ARCH=$arch
  CC=$cc
-@@ -4404,11 +4612,20 @@
+@@ -4404,11 +4613,20 @@
  CXX_O=$CXX_O
  LD_O=$LD_O
  LD_LIB=$LD_LIB
@@ -567,7 +577,7 @@
  YASMFLAGS=$YASMFLAGS
  BUILDSUF=$build_suffix
  PROGSSUF=$progs_suffix
-@@ -4448,7 +4665,7 @@
+@@ -4448,7 +4666,7 @@
  CFLAGS-ffplay=$sdl_cflags
  ZLIB=$($ldflags_filter -lz)
  LIB_INSTALL_EXTRA_CMD=$LIB_INSTALL_EXTRA_CMD
@@ -576,7 +586,7 @@
  COMPAT_OBJS=$compat_objs
  EXEOBJS=$exeobjs
  INSTALL=$install
-@@ -4456,20 +4673,20 @@
+@@ -4456,20 +4674,20 @@
  SLIBNAME=${SLIBNAME}
  SLIBNAME_WITH_VERSION=${SLIBNAME_WITH_VERSION}
  SLIBNAME_WITH_MAJOR=${SLIBNAME_WITH_MAJOR}
@@ -601,7 +611,7 @@
      eval $(awk "/#define ${name}_VERSION_M/ { print \$2 \"=\" \$3 }" "$file")
      eval ${name}_VERSION=\$${name}_VERSION_MAJOR.\$${name}_VERSION_MINOR.\$${name}_VERSION_MICRO
      eval echo "${lcname}_VERSION=\$${name}_VERSION" >> config.mak
-@@ -4513,13 +4730,21 @@
+@@ -4513,13 +4731,21 @@
                                       $ALL_COMPONENTS    \
  
  echo "#endif /* FFMPEG_CONFIG_H */" >> $TMPH
@@ -627,7 +637,7 @@
  
  cat > $TMPH <<EOF
  /* Generated by ffconf */
-@@ -4531,101 +4756,9 @@
+@@ -4531,101 +4757,9 @@
  
  echo "#endif /* AVUTIL_AVCONFIG_H */" >> $TMPH
  
